# chatroom server config

# [MySQL]
mysql_host=127.0.0.1
mysql_port=3306
mysql_user=ftpuser
mysql_password=926472
mysql_dbname=Chatroom

# [Redis]
redis_host=127.0.0.1
redis_port=6379

# [Thread Pool]
# 在 2 核环境下，过多的线程会导致 CPU 争抢和上下文切换，导致 Reactor 被饿死。
# 建议设置为核心数的 2-4 倍 (4-8)
thread_pool_size=8

# [Parser Pool]
# 协议解析线程数，建议设置为核心数 (2)
parser_thread_count=2

# [Network]
server_port=6000
# TCP Backlog，应对连接风暴
listen_backlog=4096
